package com.questio.projects.questio.utilities;


public class QuestioConstants {
    public static final String BASE_URL = "http://52.74.64.61/questio_management";
    public static final String ENDPOINT = "http://52.74.64.61/api";
    public static final String TAG_PLACE_ID = "placeid";
    public static final String TAG_PLACE_NAME = "placename";
    public static final String TAG_PLACE_FULL_NAME = "placefullname";
    public static final String TAG_PLACE_QR_CODE = "qrcode";
    public static final String TAG_PLACE_SENSOR_ID = "sensorid";
    public static final String TAG_PLACE_LATITUDE = "latitude";
    public static final String TAG_PLACE_LONGITUDE = "longitude";
    public static final String TAG_PLACE_RADIUS = "radius";
    public static final String TAG_PLACE_TYPE = "placetype";
    public static final String TAG_PLACE_IMAGEURL = "imageurl";
    public static final String QUEST_ID = "questid";
    public static final String QUEST_NAME = "questname";
    public static final String QUEST_ZONE_ID = "zoneid";
    public static final String QRTYPE_ZONE = "zone";
    public static final String QRTYPE_FLOOR = "floor";
    public static final String QRTYPE_BUILDING = "building";
    public static final String QRTYPE_PLACE = "place";
    public static final String QRTYPE_RIDDLE_ANSWER = "riddleanswer";
    public static final String ADVENTURER_PROFILE = "adventurer_profile";
    public static final String ADVENTURER_ID = "adventurer_id";
    public static final String PLACE_ID = "place_id";
    public static final String ADVENTURER_DISPLAYNAME = "adventurer_displayname";
    public static final String CURRENT_PLACE = "current_place";
    public static final String CURRENT_PLACE_TIMEOUT = "current_place_timeout";
    public static final int QUEST_NOT_STARTED = 1;
    public static final int QUEST_NOT_FINISHED = 2;
    public static final int QUEST_FINISHED = 3;
    public static final int QUEST_FAILED = 4;
    public static final int REWARD_RANK_NORMAL = 1;
    public static final int REWARD_RANK_BRONZE = 2;
    public static final int REWARD_RANK_SILVER = 3;
    public static final int REWARD_RANK_GOLD = 4;
    public static final int DEFAULT_LOCATION_INTERVAL_TIME = 2 * 60 * 1000;
    public static final String LOCATION_UPDATE_ACTION = "location.update";
    public static final int POSITION_HEAD = 1;
    public static final int POSITION_BACKGROUND = 2;
    public static final int POSITION_NECK = 3;
    public static final int POSITION_BODY = 4;
    public static final int POSITION_HANDLEFT = 5;
    public static final int POSITION_HANDRIGHT = 6;
    public static final int POSITION_ARMS = 7;
    public static final int POSITION_LEGS = 8;
    public static final int POSITION_FOOT = 9;
    public static final int POSITION_AURA = 10;
}
